// src/bundle/user/module/app.vue
<script>
import Vue from 'vue'
import { mapState, mapActions } from 'vuex'
import actions from './action.es6'

export default Vue.component('user',{
    computed:{
        ...mapState({
            user:state=>state.user.user,
            route:"route"
        })
    },
    methods:{
        ...mapActions(Object.keys(actions)),
        goBack(){
            window.history.back()
        }
    },
    created(){
        this.fetchUser('yetti')
    }
})
</script>

<template>
<div class="common-container">
    <div class="panel panel-default">
    <div class="panel-heading common-header"><button class="back-button" @click="goBack()">&lt;</button>{{user.id}}</div>
    <div class="panel-body">
        <div class="user-title">
        <img :src="user.avatar_url" alt="" />
        <span>
        <p>{{user.login}}</p>
        <p>{{user.created_at}}</p>
        </span>
    </div>
    </div>
    </div>
</div>
</template>

// src/bundle/user/module/app.jsx
import React, { Component } from 'react'
import { connected } from 'redux-container'
import * as actions from './action.es6'

export class User extends Component {
    static propTypes = {
        actions: React.PropTypes.object,
        params: React.PropTypes.object,
        user: React.PropTypes.object
    }
    componentDidMount() {
        const { fetchUser } = this.props.actions
        let user = 'yetti'
        fetchUser({ user })
    }
    render() {
        const { user } = this.props
        if (!user) {
            return null
        }
        return (
            <div className="common-container">
                <div className="panel panel-default">
                <div className="panel-heading common-header"><button className="back-button" onClick={()=>window.history.back()}>&lt;</button>{user.id}</div>
                <div className="panel-body">
                    <div className="user-title">
                    <img src={user.avatar_url} alt="" />
                    <span>
                    <p>{user.login}</p>
                    <p>{user.created_at}</p>
                    </span>
                </div>
                </div>
                </div>
            </div>
        )
    }
}

export default connected(state => state.userReducer, actions)(User)
